//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IQMedia.Service.Domain
{
    public partial class FeedsReportOutPut
    {
        #region Primitive Properties
    
        public long ID
        {
            get;
            set;
        }
    
        public string ArticleID
        {
            get;
            set;
        }
    
        public string MediaType
        {
            get;
            set;
        }
    
        public string Content
        {
            get;
            set;
        }

        #endregion
    }
}
