//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IQMedia.Service.Domain
{
    public partial class SentimentSettings
    {
        #region Primitive Properties
    
        public string TVLowThreshold
        {
            get;
            set;
        }
    
        public string TVHighThreshold
        {
            get;
            set;
        }
    
        public string NMLowThreshold
        {
            get;
            set;
        }
    
        public string NMHighThreshold
        {
            get;
            set;
        }
    
        public string SMLowThreshold
        {
            get;
            set;
        }
    
        public string SMHighThreshold
        {
            get;
            set;
        }
    
        public string TwitterLowThreshold
        {
            get;
            set;
        }
    
        public string TwitterHighThreshold
        {
            get;
            set;
        }
    
        public string PQHighThreshold
        {
            get;
            set;
        }
    
        public string PQLowThreshold
        {
            get;
            set;
        }

        #endregion
    }
}
