//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace IQMedia.Service.Domain
{
    public partial class SolrEngines
    {
        #region Primitive Properties
    
        public string MediaType
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> FromDate
        {
            get;
            set;
        }
    
        public Nullable<System.DateTime> ToDate
        {
            get;
            set;
        }
    
        public string BaseUrl
        {
            get;
            set;
        }

        #endregion
    }
}
