//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IArchiveMetaDataUpdate")]
public interface IArchiveMetaDataUpdate
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IArchiveMetaDataUpdate/WakeupService", ReplyAction="http://tempuri.org/IArchiveMetaDataUpdate/WakeupServiceResponse")]
    void WakeupService();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IArchiveMetaDataUpdateChannel : IArchiveMetaDataUpdate, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ArchiveMetaDataUpdateClient : System.ServiceModel.ClientBase<IArchiveMetaDataUpdate>, IArchiveMetaDataUpdate
{
    
    public ArchiveMetaDataUpdateClient()
    {
    }
    
    public ArchiveMetaDataUpdateClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ArchiveMetaDataUpdateClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ArchiveMetaDataUpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ArchiveMetaDataUpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void WakeupService()
    {
        base.Channel.WakeupService();
    }
}
