//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDiscoveryMetaDataUpdate")]
public interface IDiscoveryMetaDataUpdate
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiscoveryMetaDataUpdate/WakeupService", ReplyAction="http://tempuri.org/IDiscoveryMetaDataUpdate/WakeupServiceResponse")]
    void WakeupService();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDiscoveryMetaDataUpdateChannel : IDiscoveryMetaDataUpdate, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DiscoveryMetaDataUpdateClient : System.ServiceModel.ClientBase<IDiscoveryMetaDataUpdate>, IDiscoveryMetaDataUpdate
{
    
    public DiscoveryMetaDataUpdateClient()
    {
    }
    
    public DiscoveryMetaDataUpdateClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DiscoveryMetaDataUpdateClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DiscoveryMetaDataUpdateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DiscoveryMetaDataUpdateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void WakeupService()
    {
        base.Channel.WakeupService();
    }
}
