//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRequestDownload")]
public interface IRequestDownload
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRequestDownload/WakeupService", ReplyAction="http://tempuri.org/IRequestDownload/WakeupServiceResponse")]
    void WakeupService();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRequestDownloadChannel : IRequestDownload, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RequestDownloadClient : System.ServiceModel.ClientBase<IRequestDownload>, IRequestDownload
{
    
    public RequestDownloadClient()
    {
    }
    
    public RequestDownloadClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RequestDownloadClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RequestDownloadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RequestDownloadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void WakeupService()
    {
        base.Channel.WakeupService();
    }
}
